<?php

declare(strict_types=1);

namespace Pizzeria\Kitchen\Domain\ValueObject;

/**
 * Correlates 1:1 with Guest Service's OrderId, but is Kitchen's own opaque
 * type — no Shared Kernel (doc/07_define_context_map.md §6,
 * doc/08_kitchen_aggregates.md §1). Never generated by Kitchen — always
 * derived from the inbound OrderSentToKitchen payload.
 */
final class KitchenOrderId
{
    private function __construct(private readonly string $value)
    {
        if ($value === '') {
            throw new \InvalidArgumentException('KitchenOrderId cannot be empty.');
        }
    }

    public static function fromString(string $value): self
    {
        return new self($value);
    }

    public function toString(): string
    {
        return $this->value;
    }

    public function equals(self $other): bool
    {
        return $this->value === $other->value;
    }
}
